[build]
  command = "npm run build"
  publish = "dist"

# SPA fallback for client-side routing (React Router / Vite)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache static assets built by Vite
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Tip: Configure env vars in the Netlify UI or via `netlify env:set`.
# Do NOT commit secrets here.

