// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjlgmxbgxbcksvviuhmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqbGdteGJneGJja3N2dml1aG1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNzEyODIsImV4cCI6MjA2ODk0NzI4Mn0.bQ5p_0IfeL7aGLkUHsSTiwr_PALHXkMjHpU5CJ2fvRY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});